### ISSUE TITLE
Arducam Mini with Teensy 3.2

### ISSUE THREAD

**Issue by hbbeytur** [sumotoy/ArduCAM#1]
Thank you for your modification. I recently tested your code for Arducam with teensy 3.2, but I faced with some errors. Since I'm not expert in the topic I need some help. When I compiled the ArduCAM_Mini_2MP_TimeElapse2SD code, I encountered below error.
If you can help I will appreciate. Thanks. 

Arduino:1.6.8 (Mac OS X), TD: 1.28, Kart:"Teensy 3.2 / 3.1, Serial, 96 MHz optimized (overclock), US English"

Derleme seçenekleri değiştirildi, tümü yeniden derleniyor.
In file included from /Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.h:195:0,
                 from /Applications/Arduino.app/Contents/Java/libraries/ArduCAM-teensysupport_notoriginal/examples/mini/ArduCAM_Mini_2MP_TimeElapse2SD/ArduCAM_Mini_2MP_TimeElapse2SD.ino:17:
/Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/HW_AVR_SPI_defines.h:34:0: warning: "pgm_read_word" redefined [enabled by default]
 #define pgm_read_word(data) _data
 ^
In file included from /Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/WProgram.h:11:0,
                 from /Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/Arduino.h:1,
                 from /var/folders/m5/9v5cfd797hx_1mhvxhtlr6th0000gn/T/build08917ada96b34ff66407c8962bdf5b7d.tmp/sketch/ArduCAM_Mini_2MP_TimeElapse2SD.ino.cpp:1:
/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/avr/pgmspace.h:80:0: note: this is the location of the previous definition
 #define pgm_read_word(addr) (_(const unsigned short _)(addr))
 ^
In file included from /Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.h:195:0,
                 from /Applications/Arduino.app/Contents/Java/libraries/ArduCAM-teensysupport_notoriginal/examples/mini/ArduCAM_Mini_2MP_TimeElapse2SD/ArduCAM_Mini_2MP_TimeElapse2SD.ino:17:
/Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/HW_AVR_SPI_defines.h:35:0: warning: "pgm_read_byte" redefined [enabled by default]
 #define pgm_read_byte(data) *data
 ^
In file included from /Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/WProgram.h:11:0,
                 from /Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/Arduino.h:1,
                 from /var/folders/m5/9v5cfd797hx_1mhvxhtlr6th0000gn/T/build08917ada96b34ff66407c8962bdf5b7d.tmp/sketch/ArduCAM_Mini_2MP_TimeElapse2SD.ino.cpp:1:
/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/avr/pgmspace.h:79:0: note: this is the location of the previous definition
 #define pgm_read_byte(addr) (_(const unsigned char _)(addr))
 ^
ArduCAM_Mini_2MP_TimeElapse2SD: In function 'void loop()':
ArduCAM_Mini_2MP_TimeElapse2SD:82: warning: unused variable 'n' 
   static int n = 0;
              ^
ArduCAM_Mini_2MP_TimeElapse2SD:125: warning: 'temp_last' may be used uninitialized in this function 
   while ( (temp != 0xD9) | (temp_last != 0xFF))
   ^
In file included from /Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.h:195:0,
                 from /Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.cpp:53:
/Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/HW_AVR_SPI_defines.h:34:0: warning: "pgm_read_word" redefined [enabled by default]
 #define pgm_read_word(data) *data
 ^
In file included from /Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/WProgram.h:11:0,
                 from /Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/Arduino.h:1,
                 from /Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.h:194,
                 from /Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.cpp:53:
/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/avr/pgmspace.h:80:0: note: this is the location of the previous definition
 #define pgm_read_word(addr) (_(const unsigned short _)(addr))
 ^
In file included from /Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.h:195:0,
                 from /Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.cpp:53:
/Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/HW_AVR_SPI_defines.h:35:0: warning: "pgm_read_byte" redefined [enabled by default]
 #define pgm_read_byte(data) *data
 ^
In file included from /Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/WProgram.h:11:0,
                 from /Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/Arduino.h:1,
                 from /Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.h:194,
                 from /Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.cpp:53:
/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/avr/pgmspace.h:79:0: note: this is the location of the previous definition
 #define pgm_read_byte(addr) (_(const unsigned char *)(addr))
 ^
/Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.cpp: In member function 'int UTFT::bus_write(int, int)':
/Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.cpp:103:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
/Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.cpp: In member function 'void UTFT::printNumF(double, byte, int, int, char, int, char)':
/Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.cpp:835:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i=0; i<sizeof(st); i++)
                            ^
/Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.cpp:845:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for (int i=1; i<sizeof(st); i++)
                             ^
/Applications/Arduino.app/Contents/Java/libraries/UTFT4ArduCAM_SPI/UTFT_SPI.cpp:851:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for (int i=0; i<sizeof(st); i++)
                             ^
/var/folders/m5/9v5cfd797hx_1mhvxhtlr6th0000gn/T/build08917ada96b34ff66407c8962bdf5b7d.tmp/core/core.a(nonstd.c.o): In function `ltoa':
/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/nonstd.c:37: multiple definition of`ultoa'
/var/folders/m5/9v5cfd797hx_1mhvxhtlr6th0000gn/T/build08917ada96b34ff66407c8962bdf5b7d.tmp/core/core.a(itoa.c.o):/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/itoa.c:156: first defined here
/Applications/Arduino.app/Contents/Java/hardware/tools/arm/bin/../lib/gcc/arm-none-eabi/4.8.4/../../../../arm-none-eabi/bin/ld: Disabling relaxation: it will not work with multiple definitions
/var/folders/m5/9v5cfd797hx_1mhvxhtlr6th0000gn/T/build08917ada96b34ff66407c8962bdf5b7d.tmp/core/core.a(nonstd.c.o): In function `dtostrf':
/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/nonstd.c:59: multiple definition of`ltoa'
/var/folders/m5/9v5cfd797hx_1mhvxhtlr6th0000gn/T/build08917ada96b34ff66407c8962bdf5b7d.tmp/core/core.a(itoa.c.o):/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/itoa.c:101: first defined here
collect2: error: ld returned 1 exit status
Error compiling for board Teensy 3.2 / 3.1.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by sumotoy** [comment]
You should notice that I only fix the ArduCam library, not the other libraries inside examples that was created by the original author, Lee, and has some errors.
In your case you got strange errors, try get Arduino 1.6.8 and last Teensyduino 1.28.

To get this example compiling on my Teensy 3.2 I commented UTFT_SPI library since it's not used (and will never work with teensy).
Also Wire1 should be Wire.
for the SD library, there's an error probably caused by using an old version by Lee,
  `outFile = SD.open(str, O_WRITE | O_CREAT | O_TRUNC);`
should be
  `outFile = SD.open(str, FILE_WRITE);`
This fix the errors and I got compiling correctly (see below):

Using library SPI at version 1.0 in folder: C:\Arduino\168\hardware\teensy\avr\libraries\SPI 
Using library Wire at version 1.0 in folder: C:\Arduino\168\hardware\teensy\avr\libraries\Wire 
Using library SD at version 1.0.8 in folder: C:\Arduino\168\hardware\teensy\avr\libraries\SD 
Using library ArduCAM in folder: C:\ArduinoSketches\libraries\ArduCAM (legacy)

Sketch uses 36,728 bytes (14%) of program storage space. Maximum is 262,144 bytes.
Global variables use 8,712 bytes (13%) of dynamic memory, leaving 56,824 bytes for local variables. Maximum is 65,536 bytes.

**Comment by hbbeytur** [comment]
Yeah, you are quite right. After I did disable UTFT library, manny errors disappeared. But still there is something wrong. I'm using the last versions of compilers as you mentioned.

ERROR >>>>

Arduino:1.6.8 (Mac OS X), TD: 1.28, Kart:"Teensy 3.2 / 3.1, Serial, 96 MHz optimized (overclock), US English"

Derleme seçenekleri değiştirildi, tümü yeniden derleniyor.
ArduCAM_Mini_2MP_TimeElapse2SD: In function 'void loop()':
ArduCAM_Mini_2MP_TimeElapse2SD:82: warning: unused variable 'n' 
   static int n = 0;
              ^
ArduCAM_Mini_2MP_TimeElapse2SD:125: warning: 'temp_last' may be used uninitialized in this function 
   while ( (temp != 0xD9) | (temp_last != 0xFF))
   ^
/var/folders/m5/9v5cfd797hx_1mhvxhtlr6th0000gn/T/build08917ada96b34ff66407c8962bdf5b7d.tmp/core/core.a(nonstd.c.o): In function `ltoa':
/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/nonstd.c:37: multiple definition of`ultoa'
/var/folders/m5/9v5cfd797hx_1mhvxhtlr6th0000gn/T/build08917ada96b34ff66407c8962bdf5b7d.tmp/core/core.a(itoa.c.o):/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/itoa.c:156: first defined here
/Applications/Arduino.app/Contents/Java/hardware/tools/arm/bin/../lib/gcc/arm-none-eabi/4.8.4/../../../../arm-none-eabi/bin/ld: Disabling relaxation: it will not work with multiple definitions
/var/folders/m5/9v5cfd797hx_1mhvxhtlr6th0000gn/T/build08917ada96b34ff66407c8962bdf5b7d.tmp/core/core.a(nonstd.c.o): In function `dtostrf':
/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/nonstd.c:59: multiple definition of`ltoa'
/var/folders/m5/9v5cfd797hx_1mhvxhtlr6th0000gn/T/build08917ada96b34ff66407c8962bdf5b7d.tmp/core/core.a(itoa.c.o):/Applications/Arduino.app/Contents/Java/hardware/teensy/avr/cores/teensy3/itoa.c:101: first defined here
collect2: error: ld returned 1 exit status
Error compiling for board Teensy 3.2 / 3.1.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by sumotoy** [comment]
Please read again may last message, I slight changed.
Btw looks like you have a corrupted installation of Arduino/Teensy!
Those errors are in core, not in library!
I suggest a clean installation (after erase old one).

**Comment by hbbeytur** [comment]
Yes thank you very much, I reinstall the compilers and everything works well.
