### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by ghost** [sumotoy/ArduCAM#9]
Hello,
I can't compile your code sample because I get `'class ArduCAM' has no member named 'CS_HIGH'`.
What can I do to solve this?

Regards

**Comment by UCTRONICS** [comment]
@yq8
Hi,
Which platform do you use?

Regards.

**Comment by ghost** [comment]
Windows 10 x64.

**Comment by UCTRONICS** [comment]
@yq8
Hi,
Have you put our ArduCAM library to the ..\Arduino\libraries ?
Regards,

**Comment by ghost** [comment]
Apparently I deleted the folder and redownloaded it.
It works now - so most likely the issue was indeed a invalid path/file.
